baseURL = 'http://web.pinet.ar/'
languageCode = 'es-es'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "nosotros"
    weight = 1
    url = "about"

[params]
author = "Pi.Net Soluciones"
user = "pinetvpc"
hostname = "gmail.com"
footerHtml = '"Todo se conecta"'

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "whatsapp"
url = "https://api.whatsapp.com/send?phone=5493413226400"
icon = "fab fa-whatsapp whatsapp-icon" # Add link to your icon font to `layouts/partials/custom-head.html`

[[params.social]]
key = 1
name = "telegram"
url = "https://t.me/pablopinet"
rel = "me"  # You can also add rel to social link
icon = "fab fa-telegram"

[[params.social]]
key = 2
name = "facebook"
url = "https://www.facebook.com/PinetRedes"
icon = "fab fa-facebook"

[[params.social]]
key = 3
name = "instagram"
url = "https://www.instagram.com/pi.net.soluciones/?igshid=OGQ5ZDc2ODk2ZA%3D%3D"
icon = "fab fa-instagram"

[[params.social]]
key = 4
name = "email"
url = "mailto:pinetvpc@gmail.com"
icon = "fa-solid fa-envelope-open"

# [params]
# footerHtml = '"Todo se conecta"'
